//ENCODER
#ifdef ENCODER_ENABLE
//#define ENCODERS_PAD_A { E6, B0, D1 }
//#define ENCODERS_PAD_B { F7, D0, D2 }
#define ENCODERS_PAD_A { D1 }
#define ENCODERS_PAD_B { D2 }
#define ENCODER_RESOLUTION 4
#define ENCODER_DIRECTION_FLIP
#endif

#ifdef LEADER_ENABLE
#define LEADER_TIMEOUT 300
#endif